/**
 * generated by Xtext
 */
package org.rra.adaptationModel.ui.contentassist;


/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AdaptationModelDSLProposalProvider extends AbstractAdaptationModelDSLProposalProvider {
}
