/*
 * generated by Xtext
 */
package org.rra.adaptationModel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AdaptationModelDSLUiModule extends org.rra.adaptationModel.ui.AbstractAdaptationModelDSLUiModule {
	public AdaptationModelDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
