/*
* generated by Xtext
*/
package org.rra.adaptationModel.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.rra.adaptationModel.services.AdaptationModelDSLGrammarAccess;

public class AdaptationModelDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private AdaptationModelDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.rra.adaptationModel.ui.contentassist.antlr.internal.InternalAdaptationModelDSLParser createParser() {
		org.rra.adaptationModel.ui.contentassist.antlr.internal.InternalAdaptationModelDSLParser result = new org.rra.adaptationModel.ui.contentassist.antlr.internal.InternalAdaptationModelDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAdaptationRuleAccess().getAlternatives(), "rule__AdaptationRule__Alternatives");
					put(grammarAccess.getAtomicActionAccess().getAlternatives_0(), "rule__AtomicAction__Alternatives_0");
					put(grammarAccess.getOPERATORAccess().getAlternatives(), "rule__OPERATOR__Alternatives");
					put(grammarAccess.getLOGICAL_OPERATORAccess().getAlternatives(), "rule__LOGICAL_OPERATOR__Alternatives");
					put(grammarAccess.getQueryOperatorAccess().getAlternatives(), "rule__QueryOperator__Alternatives");
					put(grammarAccess.getAttributeValueAccess().getAlternatives(), "rule__AttributeValue__Alternatives");
					put(grammarAccess.getAdaptationModelAccess().getGroup(), "rule__AdaptationModel__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getAtomicRuleAccess().getGroup(), "rule__AtomicRule__Group__0");
					put(grammarAccess.getRuleSetAccess().getGroup(), "rule__RuleSet__Group__0");
					put(grammarAccess.getRuleSetAccess().getGroup_3(), "rule__RuleSet__Group_3__0");
					put(grammarAccess.getRuleSetAccess().getGroup_7(), "rule__RuleSet__Group_7__0");
					put(grammarAccess.getRuleSetAccess().getGroup_7_1(), "rule__RuleSet__Group_7_1__0");
					put(grammarAccess.getAtomicActionAccess().getGroup(), "rule__AtomicAction__Group__0");
					put(grammarAccess.getConditionActionAccess().getGroup(), "rule__ConditionAction__Group__0");
					put(grammarAccess.getConditionActionAccess().getGroup_0(), "rule__ConditionAction__Group_0__0");
					put(grammarAccess.getConditionActionAccess().getGroup_2(), "rule__ConditionAction__Group_2__0");
					put(grammarAccess.getAtomicActionWithPriorityAccess().getGroup(), "rule__AtomicActionWithPriority__Group__0");
					put(grammarAccess.getMeasurementComparisonAccess().getGroup(), "rule__MeasurementComparison__Group__0");
					put(grammarAccess.getMeasurementComparisonAccess().getGroup_3(), "rule__MeasurementComparison__Group_3__0");
					put(grammarAccess.getQueryActionAccess().getGroup(), "rule__QueryAction__Group__0");
					put(grammarAccess.getSelectActionAccess().getGroup(), "rule__SelectAction__Group__0");
					put(grammarAccess.getDeselectActionAccess().getGroup(), "rule__DeselectAction__Group__0");
					put(grammarAccess.getModifyAttributeAccess().getGroup(), "rule__ModifyAttribute__Group__0");
					put(grammarAccess.getAdaptationModelAccess().getImportsAssignment_0(), "rule__AdaptationModel__ImportsAssignment_0");
					put(grammarAccess.getAdaptationModelAccess().getNameAssignment_2(), "rule__AdaptationModel__NameAssignment_2");
					put(grammarAccess.getAdaptationModelAccess().getFrequencyAssignment_5(), "rule__AdaptationModel__FrequencyAssignment_5");
					put(grammarAccess.getAdaptationModelAccess().getAdaptationRulesAssignment_7(), "rule__AdaptationModel__AdaptationRulesAssignment_7");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getAtomicRuleAccess().getNameAssignment_1(), "rule__AtomicRule__NameAssignment_1");
					put(grammarAccess.getAtomicRuleAccess().getConditionActionAssignment_3(), "rule__AtomicRule__ConditionActionAssignment_3");
					put(grammarAccess.getRuleSetAccess().getNameAssignment_1(), "rule__RuleSet__NameAssignment_1");
					put(grammarAccess.getRuleSetAccess().getConditionAssignment_3_2(), "rule__RuleSet__ConditionAssignment_3_2");
					put(grammarAccess.getRuleSetAccess().getActionsAssignment_5(), "rule__RuleSet__ActionsAssignment_5");
					put(grammarAccess.getRuleSetAccess().getConditionAssignment_7_1_2(), "rule__RuleSet__ConditionAssignment_7_1_2");
					put(grammarAccess.getRuleSetAccess().getActionsAssignment_7_3(), "rule__RuleSet__ActionsAssignment_7_3");
					put(grammarAccess.getConditionActionAccess().getConditionAssignment_0_2(), "rule__ConditionAction__ConditionAssignment_0_2");
					put(grammarAccess.getConditionActionAccess().getAtomicActionsAssignment_1(), "rule__ConditionAction__AtomicActionsAssignment_1");
					put(grammarAccess.getConditionActionAccess().getElseAssignment_2_1(), "rule__ConditionAction__ElseAssignment_2_1");
					put(grammarAccess.getAtomicActionWithPriorityAccess().getPriorityValueAssignment_1(), "rule__AtomicActionWithPriority__PriorityValueAssignment_1");
					put(grammarAccess.getAtomicActionWithPriorityAccess().getAtomicActionAssignment_3(), "rule__AtomicActionWithPriority__AtomicActionAssignment_3");
					put(grammarAccess.getConditionAccess().getMeasurementComparisonAssignment(), "rule__Condition__MeasurementComparisonAssignment");
					put(grammarAccess.getMeasurementComparisonAccess().getMeasurementAssignment_0(), "rule__MeasurementComparison__MeasurementAssignment_0");
					put(grammarAccess.getMeasurementComparisonAccess().getOperatorAssignment_1(), "rule__MeasurementComparison__OperatorAssignment_1");
					put(grammarAccess.getMeasurementComparisonAccess().getValueAssignment_2(), "rule__MeasurementComparison__ValueAssignment_2");
					put(grammarAccess.getMeasurementComparisonAccess().getLogicalOpAssignment_3_0(), "rule__MeasurementComparison__LogicalOpAssignment_3_0");
					put(grammarAccess.getMeasurementComparisonAccess().getSecondTermAssignment_3_1(), "rule__MeasurementComparison__SecondTermAssignment_3_1");
					put(grammarAccess.getQueryActionAccess().getFeatureAssignment_3(), "rule__QueryAction__FeatureAssignment_3");
					put(grammarAccess.getQueryActionAccess().getValueAssignment_8(), "rule__QueryAction__ValueAssignment_8");
					put(grammarAccess.getSelectActionAccess().getFeatureAssignment_2(), "rule__SelectAction__FeatureAssignment_2");
					put(grammarAccess.getDeselectActionAccess().getFeatureAssignment_2(), "rule__DeselectAction__FeatureAssignment_2");
					put(grammarAccess.getModifyAttributeAccess().getFeatureAttributeAssignment_2(), "rule__ModifyAttribute__FeatureAttributeAssignment_2");
					put(grammarAccess.getModifyAttributeAccess().getAttributeValueAssignment_6(), "rule__ModifyAttribute__AttributeValueAssignment_6");
					put(grammarAccess.getStringAttributeValueAccess().getValueAssignment(), "rule__StringAttributeValue__ValueAssignment");
					put(grammarAccess.getNFRAttributeValueAccess().getValueAssignment(), "rule__NFRAttributeValue__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.rra.adaptationModel.ui.contentassist.antlr.internal.InternalAdaptationModelDSLParser typedParser = (org.rra.adaptationModel.ui.contentassist.antlr.internal.InternalAdaptationModelDSLParser) parser;
			typedParser.entryRuleAdaptationModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AdaptationModelDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AdaptationModelDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
