/*
 * generated by Xtext
 */
package org.rra.adaptationModel.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractAdaptationModelDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.rra.adaptationModel.adaptationModelDSL.AdaptationModelDSLPackage.eINSTANCE);
		return result;
	}
}
