/*
* generated by Xtext
*/
package org.rra.adaptationModel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.rra.adaptationModel.services.AdaptationModelDSLGrammarAccess;

public class AdaptationModelDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AdaptationModelDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.rra.adaptationModel.parser.antlr.internal.InternalAdaptationModelDSLParser createParser(XtextTokenStream stream) {
		return new org.rra.adaptationModel.parser.antlr.internal.InternalAdaptationModelDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AdaptationModel";
	}
	
	public AdaptationModelDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AdaptationModelDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
