/**
 * generated by Xtext
 */
package org.rra.adaptationModel.validation;


/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AdaptationModelDSLValidator extends AbstractAdaptationModelDSLValidator {
}
