/*
* generated by Xtext
*/
package org.rra.adaptationModel;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AdaptationModelDSLStandaloneSetup extends AdaptationModelDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new AdaptationModelDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

